_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 19
                - 23
                - 24
                - 55
            "4": 3.10.12
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
activation:
    value: tanh
batch_size:
    value: 64
epochs:
    value: 100
hidden_layers:
    value:
        - 64
        - 32
learning_rate:
    value: 0.07008068319249453
optimizer:
    value: sgd
